### ISSUE TITLE
I don't understand what this repo is?

### ISSUE THREAD

**Issue by alexlenail** [afgane/galaxy-tools-playbook#2]
Why does it point to another repo which seems to do the same thing @afgane?

**Comment by alexlenail** [comment]
Also, why is this the slowest part of building an image using Bjoern's image? It takes at least 5 minutes per tool! Why is this so slow?

**Comment by afgane** [comment]
This is a playbook that just wraps the [galaxy-tools role](https://github.com/galaxyproject/ansible-galaxy-tools) so the role can be used without the user needing to create the playbook to use the role and can instead clone this one. In the context of larger playbook, this playbook is not needed.

As far as the speed goes, it all depends on how long the specified tools take to install. When I run this on a toolset that's close to that of Main, it takes 2-3hrs for all the tools to install.

**Comment by alexlenail** [comment]
Is there a faster way to install tools using this playbook? Can you think of a better way than this?

**Comment by afgane** [comment]
The time it takes has nothing to do with the playbook, it's just how long the tools take to install so I don't think there's anything that can be done. One day in the desirable future, individual tools may be packaged as ready-to-use containers that we will simply be able to leverage but until then, they have to be built and that often takes time.

**Comment by bgruening** [comment]
Alex, if your tools is available through conda, installation will be as fast as possible. So get your tool conda ready :-)
On Aug 29, 2016 10:21 PM, Enis Afgan notifications@github.com wrote:The time it takes has nothing to do with the playbook, it's just how long the tools take to install so I don't think there's anything that can be done. One day in the desirable future, individual tools may be packaged as ready-to-use containers that we will simply be able to leverage but until then, they have to be built and that often takes time.
